version: "3.8"

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: wilayah_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./wilayah.sql:/docker-entrypoint-initdb.d/1-wilayah.sql
      - ./kode_pos.sql:/docker-entrypoint-initdb.d/2-kode_pos.sql
    networks:
      - app_network

  # Next.js API
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wilayah_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - app_network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: wilayah_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
